
env:
  github_token: $GIT_HUB_PERSONAL_ACCESS_TOKEN

language: node_js
node_js:
- '6'
cache:
  directories:
    - node_modules

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: www.bundlebee.io
  skip_cleanup: true
  acl: public_read
  region: us-west-2
  endpoint: http://www.bundlebee.io.s3-website-us-west-2.amazonaws.com
  detect_encoding: true
  local-dir: build
