
env:
  github_token: $GIT_HUB_PERSONAL_ACCESS_TOKEN

language: node_js
node_js:
- '6'
cache:
  directories:
    - node_modules

before_deploy:
  pip install --user awscli
deploy:
- provider: script
  script: ~/.local/bin/aws s3 sync build s3://www.bundlebee.io --region=us-west-2 --delete
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: www.bundlebee.io
  region: us-west-2
  local-dir: build
  acl: public_read
  skip_cleanup: true
