cache:
  directories:
    - node_modules
deploy:
  provider: s3
  access_key_id: "AKIAJZDFPMUN3N5EJECA"
  secret_access_key: "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"
  bucket: "www.bundlebee.io"
  skip_cleanup: true
  local_dir: build
  region: "us-west-2"
  default_text_charset: 'utf-8'

before_deploy: "echo 'ready?'"
    deploy:

    after_deploy:
      - ./after_deploy_1.sh
      - ./after_deploy_2.sh


# INFORMATION FROM TUTORIAL
language: node_js
node_js:
- '6'
services:
- mongodb
cache:
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: build
  skip_cleanup: true
  on: &2
    repo: bundlebee/website
  bucket: www.bundlebee.io
  region: us-west-2
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip